### ISSUE TITLE
contributionのimageプロパティ分岐について

### ISSUE THREAD

**Issue by ikisuke** [daikichidaze/wagumi-sbt-go#11]
Contributionのimageプロパティは、外部URLか画像をNotion内でアップロードしたかで分岐が起きます。
そのため、FileとExternalのstructをomitemptyで設定し、
https://github.com/ikisuke/wagumi-sbt-go/blob/35d5d88274791a75662a4cad827c7f15ff8062e8/notion-property.go#L13-L23

Files[0].Typeで帰ってくる文字列がfileかexternalかで分岐をかけています。
https://github.com/ikisuke/wagumi-sbt-go/blob/35d5d88274791a75662a4cad827c7f15ff8062e8/process.go#L84-L89

**Comment by daikichidaze** [comment]
変更をマージしました
https://github.com/daikichidaze/wagumi-sbt-go/commit/c653ce8028e5e4085e451a0b381ccd464048e93e#diff-d8136e514e13f0978292136c842477edbbe8059da940719abd5f7aeb14493219
