### ISSUE TITLE
Referenceの空配列表記

### ISSUE THREAD

**Issue by ikisuke** [daikichidaze/wagumi-sbt-go#12]
referenceのメモリ領域が確保されていないからか、出力後にReferenceがnullになるので
`reference := make([]string, 0)`みたいなのがあると、出力後に[]になります。

**Comment by daikichidaze** [comment]
変更をマージしました
https://github.com/daikichidaze/wagumi-sbt-go/commit/c653ce8028e5e4085e451a0b381ccd464048e93e#diff-837cc8a2afa55dfd32c6ff6d135feb979c715f582a4ee3b6250288e747f84463
