### ISSUE TITLE
Intel Macでの実行方法

### ISSUE THREAD

**Issue by ikisuke** [daikichidaze/wagumi-sbt-go#8]
## エラー
![image](https://user-images.githubusercontent.com/46296566/189515475-4b2d6927-a213-44c6-9270-ba3d2fcec5d6.png)
こちらのPCで実行しようとした時に、
`zsh: exec format error: ./wagumi-sbt-client_linux-amd64`
というエラーが出てきました。

## 解決方法
Makefile
`linux:
  GOOS=darwin GOARCH=amd64 go build -o bin/wagumi-sbt-client_linux-amd64 .`に変更

**Comment by daikichidaze** [comment]
ありがとうございます！Intel Macでもdarwinに設定するのが正解ということですね。Makefile修正します。

**Comment by daikichidaze** [comment]
Makefileに修正・追加しました。
https://github.com/daikichidaze/wagumi-sbt-go/pull/9
